import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { buildApp } from './app.js';
import { env } from './config/env.js';
import { networkHint } from './common/utils/network-hint.js';

function syncFlutterDevNetwork(): void {
  const flutterDir =
    process.env.TISEI_FLUTTER_DIR ||
    '/Users/developer/studioprojects/tisei';

  const hint = networkHint();
  if (!hint.primary) return;

  const label = hint.wifiSsid
    ? `Wi‑Fi «${hint.wifiSsid}»`
    : `Локальная сеть · ${hint.primary}`;
  const now = new Date().toISOString();
  const file = path.join(flutterDir, 'lib/config/dev_network.dart');
  const body = `// GENERATED by tisei_back on startup — не редактировать вручную.
// Обновлено: ${now}

/// LAN IP Mac, где крутится tisei_back.
const String kDevHost = '${hint.primary}';

/// Человекочитаемая сеть Mac (Wi‑Fi имя или интерфейс).
const String kDevNetworkLabel = '${label.replace(/'/g, "\\'")}';

/// Когда подсказка была снята с Mac.
const String kDevSyncedAt = '${now}';
`;
  try {
    writeFileSync(file, body, 'utf8');
    console.log(`Updated Flutter network hint → ${label} · ${hint.primary}`);
  } catch (err) {
    console.warn('Не удалось обновить Flutter dev_network.dart:', err);
  }
}

async function main() {
  const app = await buildApp();

  try {
    await app.listen({ port: env.PORT, host: env.HOST });
    const hint = networkHint();
    app.log.info(`TiSei API listening on ${env.API_BASE_URL}`);
    app.log.info(`Swagger UI: ${env.API_BASE_URL}/docs`);
    if (hint.primary) {
      app.log.info(`LAN: ${hint.label} · http://${hint.primary}:${hint.port}/api/v1`);
      for (const a of hint.addresses) {
        app.log.info(`  nic ${a.iface}: ${a.address}`);
      }
    }
    syncFlutterDevNetwork();
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
}

void main();
